name: bcs
description: Binary Canonical Serialization (BCS) in Dart.
version: 0.1.1
repository: https://github.com/mofalabs/bcs

environment:
  sdk: ">=3.0.3 <4.0.0"

dev_dependencies:
  test: ^1.26.3
  lints: ^5.0.0
