name: bcs
description: Binary Canonical Serialization (BCS) in Dart.
version: 0.1.1
repository: https://github.com/mofalabs/bcs

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
